SALESFORCE_PRACTICE PROJECT/force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>BKN-{0000}</displayFormat>
        <label>Booking ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SALESFORCE_PRACTICE PROJECT/force-app/main/default/objects/Booking__c/fields/Paying_Fare_With_Gst__c.field-meta.xml
<CustomField>
    <fullName>Paying_Fare_With_Gst__c</fullName>
    <label>Paying Fare With Gst</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

01_SALESFORCE_PRACTICE PROJECT/force-app/main/default/objects/Booking__c/fields/Seat_Class__c.field-meta.xml
<CustomField>
    <fullName>Seat_Class__c</fullName>
    <label>Seat Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Economy</fullName>
            </value>
            <value>
                <fullName>Premium Economy</fullName>
            </value>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>First Class</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MyProject/force-app/main/default/objects/Booking__c/fields/Total_Fare__c.field-meta.xml
<CustomField>
    <fullName>Total_Fare__c</fullName>
    <label>Total Fare</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

SALESFORCE_PRACTICE PROJECT/force-app/main/default/objects/GST__c/GST__c.object-meta.xml
<CustomObject>
    <label>GST</label>
    <nameField>
        <displayFormat>G-{000}</displayFormat>
        <label>GST ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GST</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

01_SALESFORCE_PRACTICE PROJECT/force-app/main/default/objects/GST__c/fields/Flying_Class__c.field-meta.xml
<CustomField>
    <fullName>Flying_Class__c</fullName>
    <label>Flying Class</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

SALESFORCE_PRACTICE PROJECT/force-app/main/default/objects/GST__c/fields/GST_VALUE__c.field-meta.xml
<CustomField>
    <fullName>GST_VALUE__c</fullName>
    <label>GST VALUE</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

SALESFORCE_PRACTICE PROJECT/force-app/main/default/classes/Cl_GSTCALCULATION_AIRLINE_MANAGEMENT.cls
public class Cl_GSTCALCULATION_AIRLINE_MANAGEMENT 
{
	public static void applygst(List<Booking__c> NBL)
    {
        List<GST__c> GST = [select Flying_Class__c,GST_VALUE__c from GST__c];
        
        Map<String,Decimal> GSTMAP = New Map<String,Decimal>();
        
        For(GST__c EG : GST)
        {
            GSTMAP.put(EG.Flying_Class__c , EG.GST_VALUE__c);
        }
        For(Booking__c EB : NBL)
        {
            EB.Paying_Fare_With_Gst__c = (GSTMAP.get(EB.Seat_Class__c)/100*EB.Total_Fare__c)+EB.Total_Fare__c;
        }
    }
}