Salesforce Practice Project/force-app/main/default/objects/Passenger_Details__c/Passenger_Details__c.object-meta.xml
<CustomObject>
    <label>Passenger Details</label>
    <nameField>
        <displayFormat>PS-{0000}-{MM}-{YYYY}</displayFormat>
        <label>Passenger ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Passenger Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MyProject/force-app/main/default/objects/Passenger_Details__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <label>FirstName</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

SALESFORCE_PRACTICE PROJECT/force-app/main/default/objects/Passenger_Details__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <label>LastName</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

01_SALESFORCE_PRACTICE PROJECT/force-app/main/default/objects/Passenger_Details__c/fields/Mobile_Number__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Number__c</fullName>
    <label>Mobile Number</label>
    <length>13</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

01_SALESFORCE_PRACTICE PROJECT/force-app/main/default/objects/Passenger_Details__c/fields/Passenger_Email_ID__c.field-meta.xml
<CustomField>
    <fullName>Passenger_Email_ID__c</fullName>
    <label>Passenger Email ID</label>
    <type>Email</type>
</CustomField>

SALESFORCE_PRACTICE PROJECT/force-app/main/default/classes/PassengerTriggerTest.cls
@istest
public class PassengerTriggerTest 
{
	@istest
    public static void EmailTest()
    {
        Passenger_Details__c P = New Passenger_Details__c();
        P.FirstName__c = 'Test';
        P.LastName__c = 'testtt';
        P.Mobile_Number__c = '99656412';
        P.Passenger_Email_ID__c = 'no@email.com';
        Insert P;
        
        System.AssertEquals('no@email.com',P.Passenger_Email_ID__c);
        System.AssertEquals('99656412', P.Mobile_Number__c);
     }
}