Salesforce Practice Project/force-app/main/default/objects/Passenger_Details__c/Passenger_Details__c.object-meta.xml
<CustomObject>
    <label>Passenger Details</label>
    <nameField>
        <displayFormat>PS-{0000}-{MM}-{YYYY}</displayFormat>
        <label>Passenger ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Passenger Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

01_SALESFORCE_PRACTICE PROJECT/force-app/main/default/objects/Passenger_Details__c/fields/Mobile_Number__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Number__c</fullName>
    <label>Mobile Number</label>
    <length>13</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

01_SALESFORCE_PRACTICE PROJECT/force-app/main/default/objects/Passenger_Details__c/fields/Passenger_Email_ID__c.field-meta.xml
<CustomField>
    <fullName>Passenger_Email_ID__c</fullName>
    <label>Passenger Email ID</label>
    <type>Email</type>
</CustomField>

SALESFORCE_PRACTICE PROJECT/force-app/main/default/classes/PassengerTriggerHandelerClass.cls
public class PassengerTriggerHandelerClass
{
	public Static Void ValidateEmail(List<Passenger_Details__c> newlist)
    {
        For(Passenger_Details__c ps : newlist)
        {
            if(ps.Passenger_Email_ID__c == null)
            {
                ps.addError('You Must & Should Put Email');
            }
        }
    }
    
    public Static Void ValidateMobile(List<Passenger_Details__c> newlist)
    {
        For(Passenger_Details__c ps : newlist)
        {
            if(ps.Mobile_Number__c == null)
            {
                ps.addError('You Must & Should Put Mobile Number');
            }
        }
    }
}